/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))

    /* CY_EINK_SPIM_SCB_IRQ */
    const cy_stc_sysint_t CY_EINK_SPIM_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)CY_EINK_SPIM_SCB_IRQ__INTC_NUMBER,
        .intrPriority = CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* CapSense_ISR */
    const cy_stc_sysint_t CapSense_ISR_cfg = {
        .intrSrc = (IRQn_Type)CapSense_ISR__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)CapSense_ISR__INTC_NUMBER,
        .intrPriority = CapSense_ISR__INTC_CORTEXM0P_PRIORITY
    };

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

