/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "pinVFan.h"
#include "pinVFan_aliases.h"
#include "pinUp.h"
#include "pinUp_aliases.h"
#include "pinDown.h"
#include "pinDown_aliases.h"
#include "pwmFan2.h"
#include "pinPWM2.h"
#include "pinPWM2_aliases.h"
#include "clkPWM2.h"
#include "clkPWM.h"
#include "statusButtons.h"
#include "clkDebounce.h"
#include "isrButton.h"
#include "lcdDisplay.h"
#include "pinMode.h"
#include "pinMode_aliases.h"
#include "pinStart.h"
#include "pinStart_aliases.h"
#include "pwmFan.h"
#include "pinPWM.h"
#include "pinPWM_aliases.h"
#include "isrUpdateDisplay.h"
#include "clkDisplay.h"
#include "adcVFan.h"
#include "rtcClock.h"
#include "eepromTime.h"
#include "lcdDisplay_LCDPort.h"
#include "lcdDisplay_LCDPort_aliases.h"
#include "adcVFan_AMux.h"
#include "adcVFan_Ext_CP_Clk.h"
#include "adcVFan_IRQ.h"
#include "adcVFan_theACLK.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"
#include "cy_em_eeprom.h"

/*[]*/

