/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "LCD.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "NC_42_aliases.h"
#include "NC_42.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Clock.h"
#include "AMux_1.h"
#include "ADC_SAR_1.h"
#include "ADC_SAR_0.h"
#include "AMux_0.h"
#include "pin_LoadSense_44_aliases.h"
#include "pin_LoadSense_44.h"
#include "pin_5Button_45_aliases.h"
#include "pin_5Button_45.h"
#include "SS_aliases.h"
#include "SS.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "pin_3_3v_49_aliases.h"
#include "pin_3_3v_49.h"
#include "pin_FM12v_48_aliases.h"
#include "pin_FM12v_48.h"
#include "pin_5v_24v_47_aliases.h"
#include "pin_5v_24v_47.h"
#include "pin_12v_46_aliases.h"
#include "pin_12v_46.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "NC_43_aliases.h"
#include "NC_43.h"
#include "PWM_Load.h"
#include "pin_12v_enable_aliases.h"
#include "pin_12v_enable.h"
#include "pin_Load_aliases.h"
#include "pin_Load.h"
#include "Clock_1.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_0_IRQ.h"
#include "ADC_SAR_0_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

