/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "CapSense_CSD.h"
#include "CapSense_CSD_CSHL.h"
#include "CapSense_CSD_TunerHelper.h"
#include "CapSense_CSD_SMS.h"
#include "CapSense_CSD_PVT.h"
#include "CapSense_CSD_IP.h"
#include "Clock_PWM.h"
#include "LED_CONTROL.h"
#include "Pin_PWM_Out.h"
#include "Pin_PWM_Out_aliases.h"
#include "LED_CONTROL_1.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "Pin_PWM_Out_1.h"
#include "Pin_PWM_Out_1_aliases.h"
#include "LCD.h"
#include "pinRS.h"
#include "pinRS_aliases.h"
#include "pinE.h"
#include "pinE_aliases.h"
#include "pinDB4.h"
#include "pinDB4_aliases.h"
#include "pinDB5.h"
#include "pinDB5_aliases.h"
#include "pinDB6.h"
#include "pinDB6_aliases.h"
#include "pinDB7.h"
#include "pinDB7_aliases.h"
#include "Pin_JoyStick.h"
#include "Pin_JoyStick_aliases.h"
#include "ADC_SAR_Seq_Button.h"
#include "pinBacklight.h"
#include "pinBacklight_aliases.h"
#include "Clock_1.h"
#include "PWMBacklight.h"
#include "CapSense_CSD_SampleClk.h"
#include "CapSense_CSD_Sns_aliases.h"
#include "CapSense_CSD_SenseClk.h"
#include "LCD_Cntl_Port.h"
#include "ADC_SAR_Seq_Button_IRQ.h"
#include "ADC_SAR_Seq_Button_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "cy_em_eeprom.h"
#include "CyLFClk.h"

/*[]*/

